version: '3'

services:
  api-gateway:
    image: dc-api-gateway:local
    container_name: dc-api-gateway
    environment:
      HTTP_PORT: 8000
      GRPC_PORT: 8800
      WORKERS_MONITORING_PERIOD_MS: 30000
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SIGNATURE: ${JWT_SIGNATURE}
    ports:
      - "8000:8000"
      - "8800:8800"
    depends_on:
      goose:
        condition: service_completed_successfully

  auth:
    image: dc-auth:local
    container_name: dc-auth
    environment:
      CONFIG_PATH: ./configs/local.yml
      JWT_SIGNATURE: ${JWT_SIGNATURE}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "44044:44044"
      - "8005:8005"
    depends_on:
      goose-auth:
        condition: service_completed_successfully
    command: [ "./app", "--config=configs/local.yml" ]

  postgres:
    image: postgres:14-alpine
    container_name: distributed-calculator-psql
    ports:
      - "5002:5432"
    environment:
      - POSTGRES_DB=distributed-calculator-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 15s
      retries: 5

  goose:
    image: artsafin/goose-migrations:latest
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./api-gateway/db/migrations:/db/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://postgres:${DB_PASSWORD}@postgres:5432/distributed-calculator-db?sslmode=disable"
    command: ["-dir", "/db/migrations", "up"]

  pg-auth:
    image: postgres:14-alpine
    container_name: dc-auth-db
    ports:
      - "5503:5503"
    expose:
      - "5503"
    command: -p 5503
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./auth/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5503" ]
      interval: 5s
      timeout: 10s
      retries: 5

  goose-auth:
    image: artsafin/goose-migrations:latest
    depends_on:
      pg-auth:
        condition: service_healthy
    volumes:
      - ./auth/db/migrations:/db/migrations
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "postgres://postgres:${DB_PASSWORD}@pg-auth:5503/auth-db?sslmode=disable"
    command: [ "-dir", "/db/migrations", "up" ]

  daemon1:
    depends_on:
      - api-gateway
    image: dc-daemon:local
    container_name: dc-daemon-1
    environment:
      #HTTP_PORT: 8001
      GRPC_PORT: 8801
      DAEMON_ID: 1
      DAEMON_HOST: "daemon1:8801"
      ORCHESTRATOR_HOST: "api-gateway:8800"
      PING_PERIOD_MS: 25000
      MAX_GOROUTINES: 1
    ports:
      - "8801:8801"

  daemon2:
    depends_on:
      - api-gateway
    image: dc-daemon:local
    container_name: dc-daemon-2
    environment:
      #HTTP_PORT: 8002
      GRPC_PORT: 8802
      DAEMON_ID: 2
      DAEMON_HOST: "daemon2:8802"
      ORCHESTRATOR_HOST: "api-gateway:8800"
      PING_PERIOD_MS: 25000
      MAX_GOROUTINES: 5
    ports:
      - "8802:8802"

  page-parser:
    depends_on:
      - api-gateway
    image: dc-page-parser:local
    container_name: dc-page-parser
    environment:
      HTTP_PORT: "8080"
      ORCHESTRATOR_HOST: "http://localhost:8000"
    ports:
      - "8080:8080"