env: "prod"

tokenTTL: 12h

http:
  port: 8080

grpc:
  port: 44044
  timeout: 5s

cache:
  ttl: 1d
  max-size: 50

db:
  port: 5003
  host: pg-auth
  db-name: auth-db
  username: postgres
  ssl-mode: disable
  max-connections: 20
  max-idle-connections: 10
